### ISSUE TITLE
Le serveur donne le Tempo - Concept 

### ISSUE THREAD

**Issue by apayetRun** [AdrianWeaver/transcendence#15]
# Le serveur donne le tempo
Nous allons créer un jeu multijoueur en ligne. Cette documentation technique explique comment nous allons gérer la partie en temps réel.

Lorsque nous créons un jeu qui ne possède pas de partie multijoueur en ligne, l'ordinateur qui lance le jeu est responsable de tous les calculs nécessaires. Cependant, cette méthode ne fonctionne pas pour une partie en ligne et en temps réel.

En effet, lorsque deux joueurs lancent le jeu simultanément, il est difficile de savoir où en est le plateau du jeu. Qui va faire en sorte de dire où en est le plateau de jeu ? Comment allons-nous synchroniser les deux parties ?

La réponse à ces questions est assez simple : nous allons ajouter un autre joueur, que nous appellerons le "serveur". Les deux autres joueurs se baseront sur les positions données par le joueur "serveur". Le joueur "serveur" ne joue pas, il effectue uniquement les calculs de positions de la balle, des deux autres joueurs, des conditions de victoire et des conditions de défaite.

En somme, nous avons un plateau de jeu géré par le serveur. Les deux autres joueurs seront simplement des télécommandes.

Ainsi, en utilisant cette méthode, nous pouvons garantir une expérience de jeu fluide et synchronisée pour tous les joueurs. Le serveur permet de centraliser toutes les informations et de les partager entre les différents joueurs, évitant ainsi les décalages et les erreurs de synchronisation.

En outre, cette méthode permet également d'éviter les tricheries, car tous les calculs sont effectués par le serveur, qui est un tiers de confiance. Les joueurs ne peuvent pas modifier les positions de la balle ou des autres joueurs, car ils n'ont pas accès aux calculs effectués par le serveur.

En résumé, le serveur est un élément clé pour gérer une partie multijoueur en ligne en temps réel. Il permet de garantir une expérience de jeu fluide et synchronisée pour tous les joueurs, ainsi que de prévenir les tricheries.

**Comment by AdrianWeaver** [comment]
Closing issue: moved to wiki.
