### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by apayetRun** [AdrianWeaver/transcendence#16]
# Stack technique.

### Cote Front

 - [ ] ReactJs : boiler plate cree avec ViteJs
 - [ ] HTML
 - [ ] CSS
 - [ ] Preprocesseur CSS
 - [ ] Axios : recuperation des donnees API
 - [ ] socket.io : communication en temps reel
 - [ ] Systeme de double auth, gAuth par exemple
 - [ ] Redux, Redux-persist, redux-thunk

 
 ### Cote back
 - [ ] NestJs
 - [ ] Envoi de mail : nodemailer && handlebars]
 - [ ] Creation d'UUID: uuid dans sa version non deprecated
 - [ ] bcrypt
 - [ ] Creation de token : JsonWebToken (JWT)
 - [ ] Reverse Proxy : NGINX
 - [ ] PostgreeSQL
 - [ ] Prisma

# Manipulation de la donnee

 1. Create
 2. Read
 3. Update
 4. Delete

Ce sont la les 4 operations de base sur la donnee. Si notre API permet de creer un "user" par exemple, elle doit permettre les autres modifications. Ca nous fait un bon CRUDite (ref. salade).

# Differents grades

 - Administrateur
 - Utilisateur
  
Ces deux grades (liste non exhaustive) permettent d'avoir differents niveau d'autorisations. Cela autorise l'acces a une route API par exemple.

# Documentation de route API.

Il est fortement recommande de documenter les routes API que l'on cree, afin de pouvoir creer les test End2End (e2e).
### Postman: creation de la documentation
Postman est largement utilisee pour tester son API pendant le developpement. Il permet donc de developper son API sans que la partie Front soit implementee. 
Il permet aussi de creer de belles documentations fortement apreciees  : https://www.postman.com/api-documentation-tool/

# Les Tests
### Jest && Cypress : Tests fonctionnels
Jest permet de tester le back, et Cypress permet de simuler graphiquement un utilisateur.
Les deux outils ont la meme syntaxe.

### Artillery: Test de charge (optionnel)
Artillery permet de simuler une charge sur le serveur  avec N utilisateurs et avec plusieurs scenarii possible.

# Recensement des vues de l'application

Cette liste est a completer et a definir. 

 

 - [ ] Accueil: Que fait-on sur cette page ?
 - [ ] Signin: 
 - [ ] Logout: 
 - [ ] Signup:
 - [ ] MyProfile:
 - [ ] Profile:
 - [ ] MatchMaking:
 - [ ] PlayGame:
 - [ ] Spectator:

**Comment by Keeghaan** [comment]
Hey, je suis justement en train d'apprendre a encrypter les mdp avec bcrypt

**Comment by nicolkaver** [comment]
De mon cote, je me penche sur l'envoie de mails :))

**Comment by apayetRun** [comment]
> De mon cote, je me penche sur l'envoie de mails :))

J'ai déjà du code fonctionnel, partie un peu technique. On attend la réunion de demain pour voir comment on s'organise de façon efficace. 😉

**Comment by apayetRun** [comment]
> Je suis justement en train d'apprendre a encrypter les mdp avec bcrypt et je regarde aussi pour les injections SQL
> 

Okay, normalement pas trop de soucis avec prisma pour ce qui est du sql. On va pouvoir se dispatcher les tâches demain.
